# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Return seq
#' 
#' Some description here
#' @title Return seq
#' @param wind A matrix to feed the regression.
#' @param window The size of the window
#' @return a list
#' @author Leandro Mineti
rcpp_seqr2 <- function(wind, window) {
    .Call('_DTScanF_rcpp_seqr2', PACKAGE = 'DTScanF', wind, window)
}

